export enum ValueInputOption {
  INPUT_VALUE_OPTION_UNSPECIFIED = "INPUT_VALUE_OPTION_UNSPECIFIED",
  RAW = "RAW",
  USER_ENTERED = "USER_ENTERED",
}

export enum InsertDataOption {
  OVERWRITE = "OVERWRITE",
  INSERT_ROWS = "INSERT_ROWS",
}
